
name: Upgrade NPM packages

on: [push]

jobs:
  upgrade-packages:
    name: Upgrade packages
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Upgrade packages
        run: npm install axios@0.24.0
        
      - name: push changes to remote
        run: |
          git config --global user.name "NodeVersionBot"
          git config --global user.email "gitbot78@gmail.com"
          git add -A
          git commit -m "commit message"
          git push
